server:
  port: 9090

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3307/chobbi}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:admin123}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 120MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
file:
  root-path: /Users/matthew777/Desktop/spring-upload-demo
  base-domain: http://localhost:9090/static


